### ISSUE TITLE
Flatpak fails to install - missing runtime

### ISSUE THREAD

**Issue by allanday** [aperezdc/revolt#79]
When I try to install the Flatpak following the instructions in the readme, I get the following:

`error: The Application org.perezdecastro.Revolt/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.24 which is not installed`

My understanding is that adding the `RuntimeRepo` to the `.flatpakref` would allow Flatpak to automatically install the missing runtime.

**Comment by aperezdc** [comment]
@allanday: There was already a `RuntimeRepo` line in [the .flatpakref file](https://github.com/aperezdc/revolt/blob/master/revolt.flatpakref). It looks like I never got to push a build to the repo after adding it. I have made locally a build against the GNOME 3.26 runtime (which I had not installed yet), and it picked the runtime automatically:

![screenshot from 2017-09-23 23-21-20](https://user-images.githubusercontent.com/723451/30776816-22d9436c-a0b6-11e7-975b-08bfdedc9dc6.png)

I have pushed this new build to the Flatpak repository. The runtime should now be picked at installation if not still installed.

**Comment by HoboPrimate** [comment]
Current [.flatpakref](https://flatpak.perezdecastro.org/revolt.flatpakref) still fails to install in Gnome Software 3.26. 

First when opening error:

No such ref 'appstream/x86_64' in remote org.perezdecastro.Revolt-origin

Then when trying to install error:

Unable to install Revolt as runtime "org.gnome.Platform" not available

**Comment by aperezdc** [comment]
@HoboPrimate: I think that's due to the mising AppStream metadata in the repository (issue #42). I don't use GNOME Software so I never got round to try installing with it... at some point I'll have to bite the bullet and fix that :innocent:
